[connection]
host = "agents.amaru.cloud"
port = 28961
timeout = "30s"
# keyfile = "/path/to/ssh/priv.key"  # Optional: defaults to OS-specific location

[application]
port = 8080
hostname = "test.example.com"
ip = "127.0.0.1"

[application.tags]
service = "application"
version = "v1.2.3"
environment = "production"
region = "us-east-1"
tier = "backend"

[application.security]
tls = false
mtls = false

[logging]
level = "debug"
# logfile = "/path/to/logs/amaru_agent.log"  # Optional: defaults to OS-specific location
