[connection]
host = "localhost"
port = 28961
user = "agent"
timeout = "30s"
keyfile = "/Users/ricardolanziano/.ssh/id_ed25519"

[application]
port = 8080
hostname = "example.com"
[application.tags]
service = "pto"
version = "v1.2.3"
environment = "production"
region = "us-east-1"
tier = "backend"
[application.security]
tls = false
mtls = false

[logging]
level = "info"
logfile = "/Users/ricardolanziano/cortex_agent.log"
